# Generated by Django 5.0.6 on 2025-12-26 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Connector",
            fields=[
                ("connector_id", models.AutoField(primary_key=True, serialize=False)),
                ("connector_name", models.CharField(max_length=255, unique=True)),
                ("connector_type", models.CharField(max_length=20)),
                ("config", models.JSONField()),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "connectors",
            },
        ),
        migrations.CreateModel(
            name="Streams",
            fields=[
                ("stream_id", models.AutoField(primary_key=True, serialize=False)),
                ("stream_name", models.CharField(max_length=255)),
                ("source_config", models.JSONField()),
                ("target_config", models.JSONField()),
                ("is_active", models.BooleanField(default=True)),
                (
                    "last_sync_status",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("last_sync_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "stream",
            },
        ),
        migrations.CreateModel(
            name="Catalog",
            fields=[
                ("catalog_id", models.AutoField(primary_key=True, serialize=False)),
                ("table_name", models.CharField(max_length=255)),
                (
                    "schema_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("table_schema", models.JSONField()),
                ("key_properties", models.JSONField(blank=True, null=True)),
                (
                    "replication_method",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "replication_key",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("is_selected", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "connector",
                    models.ForeignKey(
                        db_column="connector_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Dstream.connector",
                    ),
                ),
            ],
            options={
                "db_table": "catalog",
            },
        ),
        migrations.CreateModel(
            name="State",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("table_name", models.CharField(max_length=255)),
                (
                    "bookmark_column",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "bookmark_value",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "bookmark_type",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("records_synced", models.BigIntegerField(default=0)),
                ("last_sync_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "stream_id",
                    models.ForeignKey(
                        db_column="stream_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Dstream.streams",
                    ),
                ),
            ],
            options={
                "db_table": "state",
            },
        ),
    ]
