# Generated by Django 5.0.6 on 2025-12-26 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Dstream", "0005_state"),
    ]

    operations = [
        migrations.RenameField(
            model_name="streams",
            old_name="source_connector",
            new_name="source_config",
        ),
        migrations.RenameField(
            model_name="streams",
            old_name="target_connector",
            new_name="target_config",
        ),
        migrations.AddField(
            model_name="catalog",
            name="schema_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="state",
            name="bookmark_type",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="catalog",
            name="catalog_id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="catalog",
            name="connector_id",
            field=models.ForeignKey(
                db_column="connector_id",
                on_delete=django.db.models.deletion.CASCADE,
                to="Dstream.connector",
            ),
        ),
        migrations.AlterField(
            model_name="connector",
            name="connector_id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="state",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="state",
            name="stream_id",
            field=models.ForeignKey(
                db_column="stream_id",
                on_delete=django.db.models.deletion.CASCADE,
                to="Dstream.streams",
            ),
        ),
        migrations.AlterField(
            model_name="streams",
            name="stream_id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
